# .github/workflows/cachix.yml
name: Build and Cache
on:
  push:
    branches: [main, modularize-host-configs]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: jdguillot
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check
      - run: |
          nix flake show --json | jq -r '.nixosConfigurations | keys[]' | while read host; do
            nix build .#nixosConfigurations.$host.config.system.build.toplevel
          done
