# .github/workflows/cachix.yml
name: Build and Cache
on:
  push:
    branches: [main, modularize-host-configs]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [
            razer-nixos,
            # work-nix-wsl,
            # nixos-portable,
            # ryzn-nix-wsl,
            # sys-galp-nix,
            # thkpd-pve1,
          ]
      fail-fast: false # Continue other builds if one fails
    steps:
      - uses: actions/checkout@v3
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: jdguillot
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Remove encyrpted secrets
        run: rm -rf ./secrets
      - name: Perform Flake check before building
        run: nix flake check
      - name: Build Systems
        run: |
          nix build . --no-build-hook #nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
          # nix-collect-garbage -d
      - run: nix-shell --run "echo OK"
